<?
function import_nodes_help ($path, $arg)
{
    $output = '';
    switch ($path)
     {
        case "admin/help#import_nodes":
    	    $output = '<p>'.t("Test3 help").'</p>';
    	    break;
     }
     return $output;
} 
//=============== end function

function import_nodes_perm ()
{
    return array ('access import_nodes content','access admins page');
} 
//=============== end function


function import_nodes_menu ()
{
    $items = array();
/*
    $items['admin/settings/import_nodes'] = array(
     'title' => 'test3 module settings',
     'description' => 'Description of your settings page test3',
     'page callback' => 'drupal_get_form',// создание формы
     'page arguments' => array ('import_nodes_admin'),	// вызов функции 
     'access arguments' => array ('access administration pages'),
     'type' => MENU_NORMAL_ITEM,
    );
*/
    $items['import_nodes'] = array(
    'title' => 'Тест 3',	//Заголовок страницы
    'page callback' => 'drupal_get_form',// создание формы
    'page arguments' => array('import_nodes_form'),// вызов функции 
    'access arguments' => array('access import_nodes content')
    );
                                        
    return $items;
}
//================= end function

//===========================
//
//===========================
function import_nodes_form ($form_state)
{
	//drupal_set_message("function import_nodes_form");
/*
	$form = array();
	$form['import_nodes_wrapper'] = array(
		'#prefix' => '<div style="background:palegreen;">',
		'#value' => t('test value'),
		'#suffix' => '</div>',
	);
*/
//--------------------------------
	$form['#attributes'] = array('enctype' => "multipart/form-data");
	$form['upload']['upload_fieldset'] = array(
		'#type' => 'fieldset',
		//'#title' => t('Обновление данных о товарах и ценах'),
		'#description' => t('<strong>Для начала импорта выберите файл в формате XML.</strong>'),
		'#collapsible' => TRUE,
		'#collapsed' => false,
	);
	$form['upload']['upload_fieldset']['file_upload'] = array(
		'#type' => 'file',
		'#title' => t('File'),
		'#size' => '60',
	);
	$form['upload']['upload_fieldset']['file_upload_button'] = array(
		'#type' => 'submit',
		'#value' => t('Upload file'),
		'#submit' => array('import_nodes_add_form_submit_upload_file'),
	);

//--------------------------------
	global $base_url;
	$urls= "
<a href='update_price/remove_product'>удалить все товары каталога</a><br>
<a href='update_price/unpublic_product'>снятие товаров каталога с публикации</a><br>
<a href='update_price/public_product'>опубликовать все товары каталога</a><br>
<a href='".$base_url."/scripts/parce_csv_price.php'>parce_csv_price.php</a><br>
<a href='".$base_url."/scripts/update_price.php' target=_blank>update_price.php</a><br>";

    $form['import_nodes_wrapper']['base'] = array(
	'#prefix' => '<div style="display:none;">',
        '#type' => 'fieldset',
        '#title' => t('сервисные функции'),
	'#value' => t($urls),
        '#collapsible' => true,
        '#collapsed' => true,
    );

	return $form;
}
//================= end function

//===========================
//
//===========================
function import_nodes_admin ()
{
    $form = array();
    
    $form['sitename'] = array(
        '#type' => 'textfield',
        '#title' => t('Site'),
        '#default_value' => variable_get('sitename',''),
        '#size' => 20,
        '#maxlength' => 20,
        '#description' => t('withoutt "http://"'),
    );

    return system_settings_form ($form);
}
//========================= end function

?>
