<?php
/*
function my_module_perm()
{
    return array('access my_module content');
}
*/

function my_module_init()
{
	//drupal_set_message("function my_module_init !!!");
	//drupal_get_form('my_module_form');
}

function my_module_add_to_cart($nid, $qty, $data) {
	drupal_set_message("function my_module_add_to_cart !!!");
}

/*
function myfunc()
{
	drupal_set_message("function myfunc");
}
*/
function my_module_node_import_fields($type) {
	drupal_set_message("function my_module_node_import_fields");
//echo "<pre>";
//print_r ($type);
//echo "</pre>";
/*
  $fields = array();

  if (($node_type = node_import_type_is_node($type)) !== FALSE && uc_product_is_product($node_type)) {
//========================================
    $fields['active'] = array(
      'title' => t('Active'),
      'group' => t('uc_product_stock'),
      'weight' => 0,
    );

    $fields['stock_level'] = array(
      'title' => t('Stock level'),
      'group' => t('uc_product_stock'),
      'weight' => 1,
    );

    $fields['threshold'] = array(
      'title' => t('Threshold'),
      'group' => t('uc_product_stock'),
      'weight' => 2,
    );
//========================================
  }
  return $fields;
*/
}

function my_module_node_import_fields_alter(&$fields, $type) 
{
	drupal_set_message("function my_module_node_import_fields_alter");
//echo "<pre>";
//print_r ($fields);
//echo "</pre>";
}

function my_module_node_import_types() 
{
	drupal_set_message("function my_module_node_import_types()");
}
function my_module_node_import_types_alter(&$types) 
{
	drupal_set_message("function my_module_node_import_types_alter");
//echo "<pre>";
//print_r ($types);
//echo "</pre>";
}

function my_module_import_defaults()
{
	drupal_set_message("function my_module_import_defaults");
}

function my_module_import_values()
{
	drupal_set_message("function my_module_import_values");
}


function my_module_import_options()
{
	drupal_set_message("function my_module_import_options");
}

function my_module_import_format_options()
{
	drupal_set_message("function my_module_format_options");
}

function my_module_node_import_postprocess($type, $values, $options, $preview) 
{
	drupal_set_message("function my_module_node_import_postprocess");
}

function my_module_ca_condition() 
{
	drupal_set_message("function my_module_ca_conditionnnn");
//exit();
//echo "<pre>";
//print_r($conditions);
//var_dump(get_defined_vars());
//echo "</pre>";
}

?>
